[package]
name = "statia"
version = "0.1.1"
edition = "2021"
description = "A Universal and Lightweight, Zero dependency Rust state management library."
license-file = "LICENSE"
repository = "https://github.com/voltageddebunked/statia"
homepage = "https://statia.dev"
readme = "README.md"